export const productsData = {
  phones: [
    {
      id: "p1",
      title: "iPhone 16 Pro Max",
      rating: 5,
      price: 1299,
    //$0require("../../images/Phones/1.jpg"),
    },
    {
      id: "p2",
      title: "Samsung Galaxy S24 Ultra",
      rating: 5,
      price: 1199,
    //$0require("../../images/Phones/2.jpg"),
    },
    {
      id: "p3",
      title: "Google Pixel 9 Pro",
      rating: 4,
      price: 999,
    //$0require("../../images/Phones/3.jpg"),
    },
    {
      id: "p4",
      title: "OnePlus 12R 5G",
      rating: 4,
      price: 849,
    //$0require("../../images/Phones/4.jpg"),
    },
    {
      id: "p5",
      title: "Xiaomi 14 Ultra",
      rating: 5,
      price: 949,
    //$0require("../../images/Phones/5.jpg"),
    },
    {
      id: "p6",
      title: "ASUS ROG Phone 8",
      rating: 5,
      price: 1099,
    //$0require("../../images/Phones/6.jpg"),
    },
    {
      id: "p7",
      title: "Nothing Phone 2",
      rating: 4,
      price: 699,
    //$0require("../../images/Phones/7.jpg"),
    },
    {
      id: "p8",
      title: "Sony Xperia 1 VI",
      rating: 4,
      price: 999,
    //$0require("../../images/Phones/8.jpg"),
    },
  ],

  laptops: [
    {
      id: "l1",
      title: "MacBook Pro M3 Max",
      rating: 5,
      price: 2499,
    //$0require("../../images/Laptops/1.jpg"),
    },
    {
      id: "l2",
      title: "Dell XPS 15 OLED",
      rating: 5,
      price: 1899,
    //$0require("../../images/Laptops/2.jpg"),
    },
    {
      id: "l3",
      title: "HP Spectre x360 14",
      rating: 4,
      price: 1599,
    //$0require("../../images/Laptops/3.jpg"),
    },
    {
      id: "l4",
      title: "ASUS ZenBook 14 OLED",
      rating: 4,
      price: 1399,
    //$0require("../../images/Laptops/4.jpg"),
    },
    {
      id: "l5",
      title: "Razer Blade 16 Gaming Laptop",
      rating: 5,
      price: 2799,
    //$0require("../../images/Laptops/5.jpg"),
    },
    {
      id: "l6",
      title: "Lenovo Yoga 9i Gen 8",
      rating: 4,
      price: 1299,
    //$0require("../../images/Laptops/6.jpg"),
    },
    {
      id: "l7",
      title: "Acer Swift Go 14",
      rating: 3,
      price: 899,
    //$0require("../../images/Laptops/7.jpg"),
    },
    {
      id: "l8",
      title: "MSI Stealth 14 Studio",
      rating: 5,
      price: 1799,
    //$0require("../../images/Laptops/8.jpg"),
    },
  ],

  cameras: [
    {
      id: "c1",
      title: "Sony A7 IV Mirrorless Camera",
      rating: 5,
      price: 1999,
    //$0require("../../images/Cameras/1.jpg"),
    },
    {
      id: "c2",
      title: "Canon EOS R6 Mark II",
      rating: 5,
      price: 2499,
    //$0require("../../images/Cameras/2.jpg"),
    },
    {
      id: "c3",
      title: "Nikon Z7 II",
      rating: 4,
      price: 2299,
    //$0require("../../images/Cameras/3.jpg"),
    },
    {
      id: "c4",
      title: "Fujifilm X-T5",
      rating: 4,
      price: 1699,
    //$0require("../../images/Cameras/4.jpg"),
    },
    {
      id: "c5",
      title: "Panasonic Lumix GH6",
      rating: 5,
      price: 1999,
    //$0require("../../images/Cameras/5.jpg"),
    },
    {
      id: "c6",
      title: "DJI Pocket 3 Creator Combo",
      rating: 5,
      price: 799,
    //$0require("../../images/Cameras/6.jpg"),
    },
    {
      id: "c7",
      title: "GoPro Hero 13 Black",
      rating: 4,
      price: 599,
    //$0require("../../images/Cameras/7.jpg"),
    },
    {
      id: "c8",
      title: "Insta360 X4",
      rating: 4,
      price: 649,
    //$0require("../../images/Cameras/8.jpg"),
    },
  ],

  watches: [
    {
      id: "w1",
      title: "Apple Watch Series 10",
      rating: 5,
      price: 549,
    //$0require("../../images/Watches/1.jpg"),
    },
    {
      id: "w2",
      title: "Samsung Galaxy Watch 7",
      rating: 4,
      price: 449,
    //$0require("../../images/Watches/2.jpg"),
    },
    {
      id: "w3",
      title: "Google Pixel Watch 2",
      rating: 4,
      price: 399,
    //$0require("../../images/Watches/3.jpg"),
    },
    {
      id: "w4",
      title: "Garmin Fenix 8 Pro",
      rating: 5,
      price: 799,
    //$0require("../../images/Watches/4.jpg"),
    },
    {
      id: "w5",
      title: "Fitbit Charge 7",
      rating: 3,
      price: 199,
    //$0require("../../images/Watches/5.jpg"),
    },
    {
      id: "w6",
      title: "Huawei Watch GT 5",
      rating: 4,
      price: 349,
    //$0require("../../images/Watches/6.jpg"),
    },
    {
      id: "w7",
      title: "Amazfit T-Rex Ultra",
      rating: 4,
      price: 299,
    //$0require("../../images/Watches/7.jpg"),
    },
    {
      id: "w8",
      title: "Fossil Gen 7 Hybrid",
      rating: 3,
      price: 249,
    //$0require("../../images/Watches/8.jpg"),
    },
  ],

  headphones: [
    {
      id: "h1",
      title: "Sony WH-1000XM5",
      rating: 5,
      price: 399,
    //$0require("../../images/Headphones/1.jpg"),
    },
    {
      id: "h2",
      title: "Apple AirPods Max",
      rating: 5,
      price: 549,
    //$0require("../../images/Headphones/2.jpg"),
    },
    {
      id: "h3",
      title: "Bose QuietComfort Ultra",
      rating: 5,
      price: 499,
    //$0require("../../images/Headphones/3.jpg"),
    },
    {
      id: "h4",
      title: "Sennheiser Momentum 4 Wireless",
      rating: 4,
      price: 379,
    //$0require("../../images/Headphones/4.jpg"),
    },
    {
      id: "h5",
      title: "Beats Studio Pro",
      rating: 4,
      price: 349,
    //$0require("../../images/Headphones/5.jpg"),
    },
    {
      id: "h6",
      title: "Audio-Technica ATH-M50xBT2",
      rating: 4,
      price: 299,
    //$0require("../../images/Headphones/6.jpg"),
    },
    {
      id: "h7",
      title: "JBL Tour One M2",
      rating: 4,
      price: 279,
    //$0require("../../images/Headphones/7.jpg"),
    },
    {
      id: "h8",
      title: "Marshall Major IV",
      rating: 3,
      price: 199,
    //$0require("../../images/Headphones/8.jpg"),
    },
  ],

  gaming: [
    {
      id: "g1",
      title: "PlayStation 5 Slim",
      rating: 5,
      price: 499,
    //$0require("../../images/Gaming/1.jpg"),
    },
    {
      id: "g2",
      title: "Xbox Series X",
      rating: 5,
      price: 499,
    //$0require("../../images/Gaming/2.jpg"),
    },
    {
      id: "g3",
      title: "Nintendo Switch OLED",
      rating: 4,
      price: 349,
    //$0require("../../images/Gaming/3.jpg"),
    },
    {
      id: "g4",
      title: "Steam Deck OLED 1TB",
      rating: 5,
      price: 649,
    //$0require("../../images/Gaming/4.jpg"),
    },
    {
      id: "g5",
      title: "Razer Wolverine V2 Pro Controller",
      rating: 4,
      price: 249,
    //$0require("../../images/Gaming/5.jpg"),
    },
    {
      id: "g6",
      title: "Logitech G Pro X Superlight 2",
      rating: 4,
      price: 159,
    //$0require("../../images/Gaming/6.jpg"),
    },
    {
      id: "g7",
      title: "ASUS ROG Ally Z1 Extreme",
      rating: 5,
      price: 799,
    //$0require("../../images/Gaming/7.jpg"),
    },
    {
      id: "g8",
      title: "Meta Quest 3 VR Headset",
      rating: 5,
      price: 499,
    //$0require("../../images/Gaming/8.jpg"),
    },
  ],

  accessories: [
    {
      id: "a1",
      title: "Apple MagSafe Charger",
      rating: 4,
      price: 49,
    //$0require("../../images/Accessories/1.jpg"),
    },
    {
      id: "a2",
      title: "Anker GaNPrime 65W Charger",
      rating: 5,
      price: 59,
    //$0require("../../images/Accessories/2.jpg"),
    },
    {
      id: "a3",
      title: "Logitech MX Master 4 Mouse",
      rating: 5,
      price: 129,
    //$0require("../../images/Accessories/3.jpg"),
    },
    {
      id: "a4",
      title: "Keychron K8 Pro Mechanical Keyboard",
      rating: 4,
      price: 99,
    //$0require("../../images/Accessories/4.jpg"),
    },
    {
      id: "a5",
      title: "Belkin 3-in-1 MagSafe Charging Stand",
      rating: 5,
      price: 149,
    //$0require("../../images/Accessories/5.jpg"),
    },
    {
      id: "a6",
      title: "Samsung 2TB Portable SSD T9",
      rating: 5,
      price: 229,
    //$0require("../../images/Accessories/6.jpg"),
    },
    {
      id: "a7",
      title: "Elgato Stream Deck MK.2",
      rating: 5,
      price: 179,
    //$0require("../../images/Accessories/7.jpg"),
    },
    {
      id: "a8",
      title: "SanDisk Ultra 1TB microSDXC",
      rating: 4,
      price: 119,
    //$0require("../../images/Accessories/8.jpg"),
    },
  ],

  smartlife: [
    {
      id: "s1",
      title: "Amazon Echo Show 10",
      rating: 5,
      price: 249,
    //$0require("../../images/Smartlife/1.jpg"),
    },
    {
      id: "s2",
      title: "Google Nest Hub Max",
      rating: 4,
      price: 229,
    //$0require("../../images/Smartlife/2.jpg"),
    },
    {
      id: "s3",
      title: "Philips Hue Starter Kit",
      rating: 5,
      price: 179,
    //$0require("../../images/Smartlife/3.jpg"),
    },
    {
      id: "s4",
      title: "Ring Video Doorbell 4",
      rating: 4,
      price: 199,
    //$0require("../../images/Smartlife/4.jpg"),
    },
    {
      id: "s5",
      title: "TP-Link Kasa Smart Plug 4-Pack",
      rating: 5,
      price: 69,
    //$0require("../../images/Smartlife/5.jpg"),
    },
    {
      id: "s6",
      title: "iRobot Roomba j7+",
      rating: 5,
      price: 899,
    //$0require("../../images/Smartlife/6.jpg"),
    },
    {
      id: "s7",
      title: "Dyson Purifier Cool AutoReact",
      rating: 4,
      price: 649,
    //$0require("../../images/Smartlife/7.jpg"),
    },
    {
      id: "s8",
      title: "Nanoleaf Shapes Light Panels Kit",
      rating: 5,
      price: 249,
    //$0require("../../images/Smartlife/8.jpg"),
    },
  ],
};
export default productsData;